### ISSUE TITLE
'Could not subscribe because a connection has not been established'

### ISSUE THREAD

**Issue by dylanreich** [hharnisc/python-meteor#11]
Hi, excited to use this package - I was using python-ddp, but wanted to do mongodb inserts and switched to this. However, where client.connect() and client.call() worked with python-ddp, I get this error with python-meteor when calling any method after connect:
raise MeteorClientException('Could not subscribe because a connection has not been established')

My code: 
client = MeteorClient('ws://urlimusing.com/websocket')
client.connect()

Thanks!

**Comment by ppettit** [comment]
hi  @dylanreich, @fpaboim and @dylanreich,

i've done a bunch of fixes over the last few days that i think might have got this sorted out (and #10).

could you try [my post_0.1.3_fixes branch of python-ddp](https://github.com/ppettit/python-ddp/tree/post_0.1.3_fixes) and [my post_0.1.3_fixes branch of python-meteor](https://github.com/ppettit/python-meteor/tree/post_0.1.3_fixes) and see it they solve your issues?

i think this is better than reverting to an old version of python-ddp - let me know if it works!

thanks,

paul.

**Comment by feeloo007** [comment]
Hi @ppettit,

I'm on vacation until Tuesday 20.

I can not make a return before then.

thanks,

Philippe

**Comment by feeloo007** [comment]
Hi @ppettit, 

Sorry for the delay.

Apparently, I have no more the issue 'Could not subscribe because a connection has not been established'  using [post_0.1.3_fixes branch of python-ddp](https://github.com/ppettit/python-ddp/tree/post_0.1.3_fixes) and [post_0.1.3_fixes branch of python-meteor](https://github.com/ppettit/python-meteor/tree/post_0.1.3_fixes).

Currently I have strange behavior but is certainly due tovery large collection or a nearly full filesystem on mongodb.

I subscribe to 2 collections. A little and a very big one.

While 'subscribed' event on big one has not been emited, updates on little one seems to be delayed (using synchronous or asynchronous (callback setted ) updates).

When  'subscribed' event is emited on big collection, a flood of callback on update are emitted.

But patches concerning 'Could not subscribe because a connection has not been established' seems to be ok.

thank you for your help @ppettit

**Comment by ppettit** [comment]
hi @feeloo007,

thanks for trying those patches. i'm glad the original problem seems to be fixed. we have been using them in production for a while too. 

my app only has 1 document from one collection published to the python part (though it is updated a lot) so i haven't seen the other issue you describe with multiple collections. If i get a chance i'll take a look at it. hopefully @hharnisc will get a chance to look at my pull requests too.

thanks,

paul.

**Comment by hharnisc** [comment]
I've merged in @ppettit (huge thank you!) changes and published them. To update the package run `pip install -U python-meteor` this should update both `python-meteor` and `python-ddp` to version 0.1.4
